### PR TITLE
Added error handling to prevent segfaults for bad explicit messages

### PR DESCRIPTION
**Pull request by acidtonic**
Under no circumstances should failure to decode a network packet result in a segfault. Added quick try-catch to stop buffer overrun from crashing the server after receiving a bad explicit message.

The underrun makes it through because the check before the effected function only uses a greater than guard. Limit and start are equal which passes the check until the ByteBuffer's check which has a more thorough greater than or equal check and it throws runtime_error that is never caught.

Could possibly be fixed upstream by changing the start > limit to start >= limit prior to the decode function. In the interest of time I preferred catching the exception.

Packet in Question:
Service: 0xe
Instance: 0x9
Class: 0
Attribute: 0
Payload 88 bytes.

### CODE REVIEW

**Comment by liftoff-sr** [comment]
Thank you for contributing.  I will try and get to this in the near future.
Any chance I can easily duplicate this crash, meaning: a) do I have accesses to the client tool, or b) can you send a wireshark or tcpdump export of the problem packet?    My goal is to trap this in a debugger so I get the full picture.

**Comment by acidtonic** [comment]
In case any critical infrastructure is using this to speak to PLC's I'd rather disclose privately to your email once I can get a trace together. It is easily reproducible thankfully so should be simple to fix. Give me a day or two and I'll get back to you.

**Comment by acidtonic** [comment]
Sorry was a bit delayed. Email sent. Let me know if you didn't get it.

**Comment by tswaehn** [comment]
@lfitoff-sr
Is this tested and can be used?

**Comment by liftoff-sr** [comment]
@tswaehn,
I have not looked at it yet.  It is however still very much on my to do list.  I suspect it is an improvement indeed, but I have not committed it yet because I want to be sure it is optimal, not merely an improvement.

**Comment by liftoff-sr** [comment]
I tested this issue 2-Aug-2022 can could not duplicate it with 
Packet in Question:
Service: 0xe
Instance: 0x9
Class: 0
Attribute: 0
Payload 88 bytes.

I used the ODVA conformance tool to send the get_attribute_single to the non-existent object specified.  The stack responded as it should have and that conversation is attached in the PCAP file.
I do not get any exception nor a segfault.  So we will need a better test program, something that I can *easily* use to duplicate the problem.  Otherwise we might begin to assume that another way of fixing the issue was put into the code.  I don't expect the ODVA conformance tool to use malicious packets, everything is probably well formed for the "Messaging Tool".
If you can mock up a test program using client.cc in the tools directory, something like that is what I am looking for.  And of course we should indeed handle any malicious packet.



[eip.zip](https://github.com/liftoff-sr/CIPster/files/9245633/eip.zip)

**Pull request closed without merging**
