### PR TITLE
fix: typo in sample_application

### PR DESCRIPTION
**Pull request by tswaehn**
just a minor thing

### CODE REVIEW

**Comment by liftoff-sr** [comment]
Please align the numeric column in lines 14 and 15.  And remember, no tabs in source files in this project.  Thanks.  

After that I will merge.

**Comment by tswaehn** [comment]
Sure,
I will respect your requirements.

Actually pretty responsive - that’s cool!

By the way - what is the best way on creating and registering classes together with the assemblies?


Thanks
Sven

**Comment by liftoff-sr** [comment]
On 9/4/19 2:40 PM, Sven Ginka wrote:
> By the way - what is the best way on creating and registering classes together with the
> assemblies?

I posted a brief pointer on the CIPster mailing list at freelists, as that is a more
general place to have discussions than the issue specific design of github merge requests.

**Comment by tswaehn** [comment]
I just aligned the lines 14 and 15 + created a new pull request.

**Pull request merged**
